language: node_js

node_js:
  - "14"

jobs:
  include:
    - stage: test
      script: npm t
    - stage: npm release
      if: branch = master
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
